### ISSUE TITLE
The trackers are no longer decteded, on the "control" branch if the browser is updated from the 67 version to the 68 one

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/cookie-restrictions-strict-list-study#16]
[Affected versions]:
- Firefox Devedition 68.0b9, Build ID 20190610153228

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a Firefox Devedition 67 version installed, with the "xpinstall.signatures.dev-root" pref set to "true" in the "about:config" page.
- Have the latest version of the "cookie-restrictions-strict-list" add-on installed from [here](https://bugzilla.mozilla.org/attachment.cgi?id=9071384).
- You are enrolled in the "control" branch.
	
[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click the "Hamburger menu" button and select the "Help" option.
3. Select the "About Firefox option" and click the "Restart to update Firefox" button.
4. Navigate to the "https://mozilla.github.io/tracking-test/" website and click the "Show site information" button from the left part of the "Address Bar".
5. Observe the status of the "Content Blocking" section.

[Expected result]:
- The "Blockable content detected on this site" status is displayed.

[Actual result]:
- The "No blockable content detected on this page" status is displayed.

[Notes]:
- This issue is still reproducible after browser restart.
- This issue is no longer reproducible after we update the list from the "about:url-classifier" page.
- Attached a screen recording of the issue.
![rec of the issue](https://user-images.githubusercontent.com/31243259/59365394-2da9bc80-8d41-11e9-97db-e8da3fecf889.gif)

**Comment by ericawright** [comment]
Thank you for filing this, It's interesting that it happens on updating, and specifically on the control branch. I would file this away as a Firefox quirk, possibly because of the way we are changing how the strict and basic lists are handled in 68.
Because it goes away after updating the url-classifier lists I'll mark this as 'wontfix', those lists update themselves automatically, and our data scientists are aware of this. There will be a short period of time where the list has not yet applied, they have previously stated that the time is short enough to not affect the overall experiment results.
